# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Wildsea"
license = "MIT"
licenselink = "https://github.com/tuttu/wildsea-codex/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.147.5"

[author]
  name = "Michaël De Bona"
  homepage = "https://github.com/Tuttu/wildsea-codex"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
